# mesos cpp builds needs a lot of memory
container:
  image: kmscherer/mesos-deb-packaging:bionic
  cpu: 8
  memory: 24

task:
  env:
    MESOS_TAG: 1.6.2
    TMPDIR: /build/tmp
    MAKEFLAGS: -j8
  build_script:
    - mkdir -p /build/out /build/tmp
    - ln -sf /build /tmp/cirrus-ci-build/build
    - cd /build/out
    - "../build_mesos --nominal-version $MESOS_TAG --repo https://gitbox.apache.org/repos/asf/mesos.git?tag=$MESOS_TAG --build-version 2.0.1 --configure-flags ' --disable-java ' --rename"
  deb_artifacts:
    path: "/build/*.deb"
  python_artifacts:
    path: "/build/out/mesos-repo/build/src/python/dist/*.whl"
