version: 2
jobs:
  bionic:
    docker:
      - image: mesosdebbuilder/mesos-deb-packaging:bionic
    resource_class: xlarge
    environment:
      MAKEFLAGS=-j8
    steps:
      - run:
          name: Build builder image
          command: mkdir /build/out && cd /build/out && ../build_mesos
      - store_artifacts:
          path: /build/out
          destination: bionic

workflows:
  version: 2
  build_debs:
    jobs:
      - bionic