version: 2
jobs:
  bionic:
    docker:
      - image: mesosdebbuilder/mesos-deb-packaging:bionic
    resource_class: xlarge
    environment:
      MAKEFLAGS=-j8
    steps:
      - run:
          name: Make Builder Output Directory
          command: mkdir /build/out
      - run:
          name: Builder
          command: ../build_mesos
          working_directory: /build/out
      - store_artifacts:
          path: /build/out
          destination: bionic

workflows:
  version: 2
  build_debs:
    jobs:
      - bionic