version: 2
jobs:
  bionic:
    docker:
      - image: kmscherer/mesos-deb-packaging:bionic
    environment:
      MAKEFLAGS=-j8
    steps:
      - run:
          name: Make Builder Output Directory
          command: mkdir /build/out

      - run:
          name: Builder
          command: ../build_mesos --nominal-version $MESOS_TAG --repo https://gitbox.apache.org/repos/asf/mesos.git?tag=$MESOS_TAG --build-version 2.0.1 --rename
          working_directory: /build/out

      - store_artifacts:
          path: /build/mesos.*.egg
          destination: bionic

      - store_artifacts:
          path: /build/mesos_*.deb
          destination: bionic

workflows:
  version: 2
  build:
    jobs:
      - bionic
